site_name: Tianshu
theme: readthedocs
nav:
  - '开始使用':
    - '简介': 'overview.md'
    - '安装和配置': '安装和配置.md'
    - '常规使用和快捷键': '常规使用和快捷键.md'
    - '全局Chat': '全局Chat.md'
    - '全文阅读': '全文阅读.md'
    - 'WebChat': 'WebChat.md'
  - '功能标签':
    - '功能标签类型': '功能标签/01_功能标签类型.md'
    - '[prompt] 提示词标签': '功能标签/02_[prompt] 提示词标签.md'
    - '[snippet] 提示词标签': '功能标签/03_[snippet] 提示词标签.md'
    - '[base] 本地知识库': '功能标签/04_[base] 本地知识库.md'
    - '[model] 模型标签': '功能标签/05_[model] 模型标签.md'
    - '[engine] 内置标签': '功能标签/06_[engine] 内置标签.md'
    - '[agent] 插件标签': '功能标签/07_[agent] 插件标签.md'
  - 常见问题:
    - '常见问题': '常见问题.md'

